// <auto-generated />
using System;
using Mercato.Orders.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mercato.Orders.Migrations
{
    [DbContext(typeof(OrderDbContext))]
    [Migration("20251129210530_AddReviewReports")]
    partial class AddReviewReports
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mercato.Orders.Domain.Entities.CaseItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("ReturnRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SellerSubOrderItemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ReturnRequestId");

                    b.HasIndex("SellerSubOrderItemId");

                    b.HasIndex("SellerSubOrderItemId", "ReturnRequestId")
                        .HasDatabaseName("IX_CaseItems_ItemId_RequestId");

                    b.ToTable("CaseItems");
                });

            modelBuilder.Entity("Mercato.Orders.Domain.Entities.CaseMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ReturnRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SenderRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SenderUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ReturnRequestId");

                    b.HasIndex("ReturnRequestId", "CreatedAt")
                        .HasDatabaseName("IX_CaseMessages_RequestId_CreatedAt");

                    b.ToTable("CaseMessages");
                });

            modelBuilder.Entity("Mercato.Orders.Domain.Entities.CaseStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ChangedByRole")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ChangedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("NewStatus")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("OldStatus")
                        .HasColumnType("int");

                    b.Property<Guid>("ReturnRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ReturnRequestId");

                    b.HasIndex("ReturnRequestId", "ChangedAt")
                        .HasDatabaseName("IX_CaseStatusHistories_RequestId_ChangedAt");

                    b.ToTable("CaseStatusHistories");
                });

            modelBuilder.Entity("Mercato.Orders.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BuyerEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("BuyerId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeliveryAddressLine1")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DeliveryAddressLine2")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DeliveryCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DeliveryCountry")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("DeliveryFullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DeliveryInstructions")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DeliveryPhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("DeliveryPostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DeliveryState")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("FailedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("ItemsSubtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaymentMethodName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PaymentTransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("RefundedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ShippedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("ShippingTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("PaymentTransactionId");

                    b.HasIndex("BuyerId", "CreatedAt", "Status")
                        .HasDatabaseName("IX_Orders_BuyerId_CreatedAt_Status");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Mercato.Orders.Domain.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ProductTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Mercato.Orders.Domain.Entities.ProductReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BuyerId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("ReviewText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("SellerSubOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SellerSubOrderItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SellerSubOrderId");

                    b.HasIndex("SellerSubOrderItemId")
                        .IsUnique();

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_ProductReviews_Status");

                    b.HasIndex("StoreId");

                    b.HasIndex("ProductId", "Status")
                        .HasDatabaseName("IX_ProductReviews_ProductId_Status");

                    b.ToTable("ProductReviews");
                });

            modelBuilder.Entity("Mercato.Orders.Domain.Entities.ReturnRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdminDecision")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("AdminDecisionAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("AdminDecisionByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AdminDecisionReason")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("BuyerId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CaseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CaseType")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("EscalatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EscalatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EscalationReason")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("HasNewActivity")
                        .HasColumnType("bit");

                    b.Property<string>("LastActivityByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("LinkedRefundId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal?>("RefundAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ResolutionReason")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("ResolutionType")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SellerNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("SellerSubOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.HasIndex("CaseNumber")
                        .IsUnique();

                    b.HasIndex("LinkedRefundId");

                    b.HasIndex("SellerSubOrderId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_ReturnRequests_Status");

                    b.ToTable("ReturnRequests");
                });

            modelBuilder.Entity("Mercato.Orders.Domain.Entities.ReviewReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdditionalDetails")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Reason")
                        .HasColumnType("int");

                    b.Property<string>("ReporterId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("ReviewId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ReporterId");

                    b.HasIndex("ReviewId");

                    b.HasIndex("ReviewId", "ReporterId")
                        .IsUnique()
                        .HasDatabaseName("IX_ReviewReports_ReviewId_ReporterId");

                    b.ToTable("ReviewReports");
                });

            modelBuilder.Entity("Mercato.Orders.Domain.Entities.SellerRating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BuyerId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<Guid>("SellerSubOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.HasIndex("OrderId");

                    b.HasIndex("SellerSubOrderId")
                        .IsUnique();

                    b.HasIndex("StoreId");

                    b.HasIndex("StoreId", "CreatedAt")
                        .HasDatabaseName("IX_SellerRatings_StoreId_CreatedAt");

                    b.ToTable("SellerRatings");
                });

            modelBuilder.Entity("Mercato.Orders.Domain.Entities.SellerSubOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("FailedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("ItemsSubtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("RefundedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ShippedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ShippingCarrier")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("ShippingCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShippingMethodName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SubOrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrackingNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("StoreId");

                    b.HasIndex("SubOrderNumber")
                        .IsUnique();

                    b.ToTable("SellerSubOrders");
                });

            modelBuilder.Entity("Mercato.Orders.Domain.Entities.SellerSubOrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ProductTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("SellerSubOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ShippedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SellerSubOrderId");

                    b.HasIndex("SellerSubOrderId", "Status")
                        .HasDatabaseName("IX_SellerSubOrderItems_SubOrderId_Status");

                    b.ToTable("SellerSubOrderItems");
                });

            modelBuilder.Entity("Mercato.Orders.Domain.Entities.ShippingStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ChangedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("NewStatus")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("PreviousStatus")
                        .HasColumnType("int");

                    b.Property<Guid>("SellerSubOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ShippingCarrier")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrackingNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAt");

                    b.HasIndex("SellerSubOrderId");

                    b.ToTable("ShippingStatusHistories");
                });

            modelBuilder.Entity("Mercato.Orders.Domain.Entities.CaseItem", b =>
                {
                    b.HasOne("Mercato.Orders.Domain.Entities.ReturnRequest", "ReturnRequest")
                        .WithMany("CaseItems")
                        .HasForeignKey("ReturnRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mercato.Orders.Domain.Entities.SellerSubOrderItem", "SellerSubOrderItem")
                        .WithMany()
                        .HasForeignKey("SellerSubOrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReturnRequest");

                    b.Navigation("SellerSubOrderItem");
                });

            modelBuilder.Entity("Mercato.Orders.Domain.Entities.CaseMessage", b =>
                {
                    b.HasOne("Mercato.Orders.Domain.Entities.ReturnRequest", "ReturnRequest")
                        .WithMany("Messages")
                        .HasForeignKey("ReturnRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReturnRequest");
                });

            modelBuilder.Entity("Mercato.Orders.Domain.Entities.CaseStatusHistory", b =>
                {
                    b.HasOne("Mercato.Orders.Domain.Entities.ReturnRequest", "ReturnRequest")
                        .WithMany("StatusHistory")
                        .HasForeignKey("ReturnRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReturnRequest");
                });

            modelBuilder.Entity("Mercato.Orders.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("Mercato.Orders.Domain.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Mercato.Orders.Domain.Entities.ProductReview", b =>
                {
                    b.HasOne("Mercato.Orders.Domain.Entities.SellerSubOrder", "SellerSubOrder")
                        .WithMany()
                        .HasForeignKey("SellerSubOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mercato.Orders.Domain.Entities.SellerSubOrderItem", "SellerSubOrderItem")
                        .WithMany()
                        .HasForeignKey("SellerSubOrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SellerSubOrder");

                    b.Navigation("SellerSubOrderItem");
                });

            modelBuilder.Entity("Mercato.Orders.Domain.Entities.ReturnRequest", b =>
                {
                    b.HasOne("Mercato.Orders.Domain.Entities.SellerSubOrder", "SellerSubOrder")
                        .WithMany()
                        .HasForeignKey("SellerSubOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SellerSubOrder");
                });

            modelBuilder.Entity("Mercato.Orders.Domain.Entities.ReviewReport", b =>
                {
                    b.HasOne("Mercato.Orders.Domain.Entities.ProductReview", "Review")
                        .WithMany()
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Review");
                });

            modelBuilder.Entity("Mercato.Orders.Domain.Entities.SellerRating", b =>
                {
                    b.HasOne("Mercato.Orders.Domain.Entities.SellerSubOrder", "SellerSubOrder")
                        .WithMany()
                        .HasForeignKey("SellerSubOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SellerSubOrder");
                });

            modelBuilder.Entity("Mercato.Orders.Domain.Entities.SellerSubOrder", b =>
                {
                    b.HasOne("Mercato.Orders.Domain.Entities.Order", "Order")
                        .WithMany("SellerSubOrders")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Mercato.Orders.Domain.Entities.SellerSubOrderItem", b =>
                {
                    b.HasOne("Mercato.Orders.Domain.Entities.SellerSubOrder", "SellerSubOrder")
                        .WithMany("Items")
                        .HasForeignKey("SellerSubOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SellerSubOrder");
                });

            modelBuilder.Entity("Mercato.Orders.Domain.Entities.ShippingStatusHistory", b =>
                {
                    b.HasOne("Mercato.Orders.Domain.Entities.SellerSubOrder", "SellerSubOrder")
                        .WithMany()
                        .HasForeignKey("SellerSubOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SellerSubOrder");
                });

            modelBuilder.Entity("Mercato.Orders.Domain.Entities.Order", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("SellerSubOrders");
                });

            modelBuilder.Entity("Mercato.Orders.Domain.Entities.ReturnRequest", b =>
                {
                    b.Navigation("CaseItems");

                    b.Navigation("Messages");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("Mercato.Orders.Domain.Entities.SellerSubOrder", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
